### ISSUE TITLE
能出一个安装文档么有点不会整

### ISSUE THREAD

**Issue by mogudada** [Margular/frida-skeleton#42]

**Comment by Margular** [comment]
你是指库文件安装吗，直接`pip install -r requirements`即可

**Comment by mogudada** [comment]
> 你是指库文件安装吗，`pip install -r requirements`直接即可

安装了，然后呢。不太会py=，=

**Comment by mogudada** [comment]
> 你是指库文件安装吗，`pip install -r requirements`直接即可

啊。可以成功运行了  py.exe .\frida-skeleton.py -h

**Comment by mogudada** [comment]
> 你是指库文件安装吗，直接`pip install -r requirements`即可

不好意思在咨询下 下面报错改怎么处理
```
python ./frida-skeleton.py -i
Traceback (most recent call last):
  File "./frida-skeleton.py", line 78, in <module>
    main = FridaSkeleton()
  File "./frida-skeleton.py", line 43, in __init__
    Adb.start_server()
  File "C:\Users\moguj\Desktop\快手空间\frida-skeleton\lib\utils\adb.py", line 18, in start_server
    return Shell().exec('adb start-server', supress_error=True)
  File "C:\Users\moguj\Desktop\快手空间\frida-skeleton\lib\utils\shell.py", line 25, in exec
    err = p.stderr.read().decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte

```


```
python ./frida-skeleton.py -svip 8080 margular                                                                                                
 [2020-09-07 21:03:59] [DEBUG] [Shell] adb start-server
Traceback (most recent call last):
  File "./frida-skeleton.py", line 78, in <module>
    main = FridaSkeleton()
  File "./frida-skeleton.py", line 43, in __init__
    Adb.start_server()
  File "C:\Users\moguj\Desktop\快手空间\frida-skeleton\lib\utils\adb.py", line 18, in start_server
    return Shell().exec('adb start-server', supress_error=True)
  File "C:\Users\moguj\Desktop\快手空间\frida-skeleton\lib\utils\shell.py", line 25, in exec
    err = p.stderr.read().decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte
```

**Comment by Margular** [comment]
我这边没出现过这个原因，你试着google看能否解决，你这个看提示应该是编码问题，尝试把涉及到的字符全改成英文，可能是中文引起的，自己实在解决不了的话提供下详细的信息，例如你用的apk是什么，手机是什么型号，运行环境什么的，我可以帮你看，先尝试google看看能否解决

**Comment by mogudada** [comment]
> 我这边没出现过这个原因，你试着google看能否解决，你这个看提示应该是编码问题，尝试把涉及到的字符全改成英文，可能是中文引起的，自己实在解决不了的话提供下详细的信息，例如你用的apk是什么，手机是什么型号，运行环境什么的，我可以帮你看，先尝试google看看能否解决
 
shell.py 文件设置成ANSI编码格式成功了
  ```
      en = "ANSI"
        # output processing
        out = p.stdout.read().decode(en).strip()
        ret.out = out
        err = p.stderr.read().decode(en).strip()
```
