### ISSUE TITLE
使用命令 -vip  是报错

### ISSUE THREAD

**Issue by pow-ss** [Margular/frida-skeleton#59]
模拟器是夜神加burp，按照requirements安装的依赖包，
报错如下
[2021-09-02 04:29:42] [DEBUG] [Shell] adb start-server
Traceback (most recent call last):
  File "D:\frida-skeleton\frida-skeleton.py", line 86, in <module>
    skeleton.start()
  File "D:\frida-skeleton\frida-skeleton.py", line 50, in start
    Adb.start_server()
  File "D:\frida-skeleton\lib\utils\adb.py", line 18, in start_server
    return Shell().exec('adb start-server', supress_error=True)
  File "D:\frida-skeleton\lib\utils\shell.py", line 20, in exec
    p = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE, close_fds=True)
  File "C:\Users\19804\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\19804\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Margular** [comment]
环境变量里面添加adb，你这个错误是python没找到adb

**Comment by Margular** [comment]
老哥问题解决了吗 :/

**Comment by pow-ss** [comment]
> 老哥问题解决：/

OK  我试一下，感谢！
