### ISSUE TITLE
全英文的路径运行报错

### ISSUE THREAD

**Issue by Wrin9** [Margular/frida-skeleton#66]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte

**Comment by Margular** [comment]
能否提供一下全部的报错信息呢？

**Comment by a59921268** [comment]
Traceback (most recent call last):
  File "D:\gits\frida-skeleton-master\frida-skeleton-master\frida-skeleton.py", line 86, in <module>
    skeleton.start()
  File "D:\gits\frida-skeleton-master\frida-skeleton-master\frida-skeleton.py", line 50, in start
    Adb.start_server()
  File "D:\gits\frida-skeleton-master\frida-skeleton-master\lib\utils\adb.py", line 18, in start_server
    return Shell().exec('adb start-server', supress_error=True)
  File "D:\gits\frida-skeleton-master\frida-skeleton-master\lib\utils\shell.py", line 25, in exec
    err = p.stderr.read().decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte

**Comment by Margular** [comment]
这是个已知问题，原因是windows控制台默认的编码不是utf-8导致的，后续会更新解决，临时解决方案可以修改下代码
`err = p.stderr.read().decode().strip()`
这句修改成
`err = p.stderr.read().decode(encoding='gbk').strip()`
如果问题依旧存在，则改为
`err = p.stderr.read().decode(encoding='gbk', errors='backslashreplace').strip()`
